### ISSUE TITLE
When using the API key, widget breaks

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/GoogleMapsWidget#11]
After upgrading everything to the latest version for my 6.3 upgrade, the GoogleMaps widget breaks when I have the API key filled in. This can also be reproduced in the test project.

Appstore version 5.4 of the widget is still OK

![image](https://cloud.githubusercontent.com/assets/6723899/13539700/4368d166-e252-11e5-88c5-c3db2d73d6a4.png)

**Comment by JelteMX** [comment]
I think there was some type of typo in one of the pull requests. Can you check this version? https://github.com/mendix/GoogleMapsWidget/raw/master/test/widgets/GoogleMaps.mpk

**Comment by JelteMX** [comment]
Tested and fixed

**Comment by mgroeneweg** [comment]
Indeed. Speedy Gonzales did it again! :-)
