### ISSUE TITLE
Option should be present to disable drag and zooming 

### ISSUE THREAD

**Issue by hodchUX** [mendix/GoogleMapsWidget#14]
There should be more options to customise the appearance of google maps. Including disabling scrolling, dragging and zooming. To have a static map.

**Comment by JelteMX** [comment]
[Reference](https://developers.google.com/maps/documentation/javascript/reference?csw=1#MapOptions). Good idea

**Comment by JelteMX** [comment]
Fixed in [6.0.1](https://github.com/mendix/GoogleMapsWidget/releases/tag/v6.0.1)
